Remove redundant Hash#destroy patch from Internal TestHelpers
The monkey patch for `Hash#destroy` is introduced in this commit.
[https://github.com/NoamB/sorcery/commit/f8646b77ca5eee9f7dad47d67047f4119f4f262b#diff-769521652f47338fa5a75da5a8fa4bedd213e348549d390d46bb6eac8c826bb7R3-R10](https://github.com/NoamB/sorcery/commit/f8646b77ca5eee9f7dad47d67047f4119f4f262b#diff-769521652f47338fa5a75da5a8fa4bedd213e348549d390d46bb6eac8c826bb7R3-R10)

I assume it is added to avoid this issue.

[NoMethodError: undefined method `destroy_session' for nil:NilClass · Issue #464 · NoamB/sorcery](https://github.com/NoamB/sorcery/issues/464)

However, this is a problem only up to Rails 4.0.
In Rails 4.1, the following change is introduced and the exception no longer occurs.

[Calling reset_session inside of a controller with a NullSessionHash raises a nil exception. by jbaudanza · Pull Request #12279 · rails/rails](https://github.com/rails/rails/pull/12279)

Because of this, this monkey patch is no longer needed now.